### ISSUE TITLE
src/mproto.c line:58 - переменная в условии цикла

### ISSUE THREAD

**Issue by Muzalevsky** [KaiL4eK/madproto#1]
src/mproto.c line:58 for ( size_t i = 0; i < len; i++ ) {

[link to file](https://github.com/KaiL4eK/madproto/blob/master/src/mproto.c)

переменная "i" объявлена в условии цикла. Это есть не очень хорошо для совместимости со всякими экскрементами мамонта...

**Comment by KaiL4eK** [comment]
Спасибо! Можно ссылки прямо на строки добавлять) Кликаешь на номер строки и Copy Permalink

https://github.com/KaiL4eK/madproto/blob/28f2f5f1e610240539097bfa2d95fe820b35d8c1/src/mproto.c#L58

**Comment by KaiL4eK** [comment]
Проведу более широку проверку на поддержку С99 - думаю этого достаточно, чтобы не углубляться до стандартов более ранних

**Comment by KaiL4eK** [comment]
Думаю, стоит отталкиваться от фактов. При необходимости поддержки ранних стандартов будут внесены исправления. Пока абстрактные проблемы решать рано. Если уже есть такие примеры - просьба приложить более подробную инфу о том, какой стандарт и язык (С/С++)
