### ISSUE TITLE
src/mproto.h line:31 - не указаны единицы измерения буффера.

### ISSUE THREAD

**Issue by Muzalevsky** [KaiL4eK/madproto#2]
src/mproto.h line:31 - не указаны единицы измерения буффера. Просто придираюсь, но, возможно, по делу. Охота написать что-то вроде: "Define size of input buffer **in bytes**"

[link to file](https://github.com/KaiL4eK/madproto/blob/master/src/mproto.h)

**Comment by KaiL4eK** [comment]
Сделано)
